### ISSUE TITLE
CSS Suggestion

### ISSUE THREAD

**Issue by jonsuther** [CSS-Tricks/AnythingSlider#308]
In the anythingslider.css, I think it would be helpful for people if this: 

``` css
/* Navigation buttons, default state */
div.anythingSlider .anythingControls ul a.cur, div.anythingSlider .anythingControls ul a {
    background: #777;
    color: #000;
}
```

Was replaced with this:

``` css
/* Navigation buttons, current state */
div.anythingSlider .anythingControls ul a.cur {
    background: #777;
    color: #000;
}
/* Navigation buttons, default state */
div.anythingSlider .anythingControls ul a {
    background: #777;
    color: #000;
}
```

Not a huge deal, it just took more a few minutes to figure out what I was missing when searching for how to change the current tab styling.
