### ISSUE TITLE
Need to recalculate size on window resize

### ISSUE THREAD

**Issue by wichert** [CSS-Tricks/AnythingSlider#437]
Resizing a window may influence the size of the panels in a slider. Currently anythingslider does not handle that properly: it sets a fixed widht and height on the container and the panels on initial setup, but does not update that on window resize.

**Comment by khonza** [comment]
Hello World!

How do you manually update $('#slider').data('AnythingSlider').panelSize values after slider has completely loaded? I have my own dimensions and left-scroll calculations. I have tried everything. Please help, Im new to Anything slider.

**Comment by Mottie** [comment]
Hi @khonza!

I'm not sure why you'd need to adjust the sizes. Just set the panel size using css - see [this demo](http://jsfiddle.net/Mottie/ebx1otr6/1/)

```html
<ul id="slider">
    <li class="murray"><img src="http://www.fillmurray.com/300/200" alt="" /></li>
    <li class="holder1"><img src="http://placehold.it/200x300" alt="" /></li>
    <li class="bear"><img src="http://placebear.com/400/200" alt="" /></li>
    <li class="lorem"><img src="http://lorempixel.com/500/100" alt="" /></li>
    <li class="holder2"><img src="http://placehold.it/300x300/0000ff/ffffff" alt="" /></li>
</ul>
```

```css
#slider { list-style: none; width: 300px; height: 200px; }
.murray { width: 300px; height: 200px; }
.holder1 { width: 200px; height: 300px; }
.bear { width: 400px; height 200px; }
.lorem { width: 500px; height 100px; }
.holder2 { width: 300px; height: 300px; }
```

Then make sure to set the `resizeContents` option to `false`:

```js
$('#slider').anythingSlider({
    theme: 'default',
    resizeContents: false
});
```
