### ISSUE TITLE
Constant resize when expand: true

### ISSUE THREAD

**Issue by richardtape** [CSS-Tricks/AnythingSlider#481]
Right then, this is firmly in the 'what the hell is going on here' category. So much so, I've recorded a screencast to try and explain. I've placed all my css/js at the end of the screencast, but for completeness, here it is,

``` javascript
jQuery(document).ready(function($) {

    if( $( 'body' ).hasClass( 'home' ) || $( 'body' ).hasClass( 'front-page' ) ){

        //Twitter widget anything slider
        if( $( '.widget-themeists_twitter' ).length != 0 ){

            $('.widget-themeists_twitter ul').anythingSlider({
                expand          : true,
                resizeContents  : true,
                showMultiple    : 2,
                changeBy        : 2,
                buildNavigation : false,
                buildStartStop  : false,
                hashTags        : false
            });

        }

    }


});
```

``` css
.above_footer .widget-themeists_twitter .anythingSlider
{
    overflow-y: auto;
    overflow-x: hidden;
    height: 40px;
    width: 100%;
}

.above_footer .widget-themeists_twitter li
{
    width: 45%;
    float: left;
    padding: 0;
}

    .above_footer .widget-themeists_twitter li div
    {
        padding: 0 5%;
        overflow: visible;
    }
```

Using jquery v1.8.3  and anythingSlider v1.8.9

Screencast can be seen at: https://dl.dropbox.com/u/455309/anythingslider.mp4

I'm baffled. I've almost certainly missed something, but honestly can't see what it is.
